server:
    port: 8090

kafka:
    bootstrap:
        address: localhost:29092
    schemaregistry:
        address: http://localhost:8081
    message:
        topic:
            saved: partnerSaved
            deleted: partnerDeleted