server:
    port: 8090

kafka:
    bootstrap:
        address: localhost:9092
    schemaregistry:
        address: http://localhost:8081
    message:
        topic:
            created: partnerCreated
    group:
        id: partnerGroup